"""
===============================================================================
Project: PACIOLI
Module: logic.domain.services.aggregation.card_aggregator
===============================================================================

Description:
    Domain service that aggregates card voucher records into settlement
    summaries (stg_card_settlements) and prepares the corresponding detail
    records (stg_card_details). Generates match_hash_base for settlement
    matching; the sequence counter is added by CardRepository.

Responsibilities:
    - Normalize brand codes to canonical settlement header values
      (VISA, DINERS CLUB, AMEX, PACIFICARD, OTROS).
    - Group vouchers by settlement_id + brand + establishment_name + fecha_pago
      and sum amount columns.
    - Sort settlements chronologically.
    - Generate match_hash_base (without sequence counter):
        PACIFICARD:    BRAND_BATCH_NET  (e.g., PACIFICARD_001447_178.80)
        All others:    BRAND_NET        (e.g., DINERS CLUB_141.96)
    - Generate etl_hash for settlement deduplication.
    - Add ETL metadata (etl_batch_id, reconcile_status).
    - Prepare detail records by renaming voucher columns to staging schema names.

Key Components:
    - CardAggregator: Domain service; accepts a voucher DataFrame and returns
      (df_settlements, df_details) as a tuple.

Notes:
    - v2.6: match_hash_base is generated WITHOUT the trailing counter.
      CardRepository reads card_hash_counters and appends the counter to
      produce the final match_hash_key. This separates domain logic (aggregation)
      from infrastructure concerns (counter persistence).
    - settlement_id is expected to be pre-generated by the voucher transformer
      (e.g., SVI_602_0202 for Pacificard, 68893-0202 for Guayaquil).
    - batch_number (lote) is used in PACIFICARD hash_base; it is zero-padded
      to 6 digits (e.g., 1447 -> 001447).

Dependencies:
    - pandas, numpy, hashlib, typing
    - utils.data_cleaner, utils.logger
    - logic.domain.services.hashing.historical_context_service

===============================================================================
"""

import pandas as pd
import numpy as np
import hashlib
from typing import Tuple, Optional
from utils.data_cleaner import DataCleaner
from utils.logger import get_logger
from logic.domain.services.hashing.historical_context_service import HistoricalContextService


class CardAggregator:
    """
    Domain service for aggregating card vouchers into settlement summaries.

    v2.6 design:
        CardAggregator generates match_hash_base (no counter suffix).
        CardRepository appends the counter after consulting card_hash_counters.

    Hash formats:
        PACIFICARD:  BRAND_BATCH_NET  (e.g., PACIFICARD_001447_178.80)
        All others:  BRAND_NET        (e.g., DINERS CLUB_141.96)

    Output:
        df_settlements: One row per settlement_id with aggregated amounts and
                        match_hash_base (counter added by CardRepository).
        df_details:     One row per original voucher with staging column names.
    """

    def __init__(
        self,
        context_service: Optional[HistoricalContextService] = None
    ):
        """
        Args:
            context_service: Optional HistoricalContextService instance.
                             Retained for interface compatibility; not used in v2.6
                             since counter assignment was moved to CardRepository.
        """
        self.context_service = context_service or HistoricalContextService()
        self.logger = get_logger("CARD_AGGREGATOR")

    def aggregate(
        self,
        df_vouchers: pd.DataFrame,
        brand: Optional[str] = None
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Aggregate vouchers into settlements and prepare detail records.

        Steps:
            1. Normalize brand for settlement header grouping.
            2. Group vouchers by settlement_id + brand + establishment + date.
            3. Sort settlements chronologically.
            4. Generate match_hash_base (without counter suffix).
            5. Generate etl_hash for settlement deduplication.
            6. Add ETL metadata (etl_batch_id, reconcile_status).
            7. Prepare detail records with staging column names.

        Args:
            df_vouchers: Transformed voucher DataFrame with settlement_id,
                         brand, establishment_name, fecha_pago, amount columns,
                         voucher_hash_key, etl_hash, and lote (for PACIFICARD).
            brand: Optional default brand string if 'brand' column is absent.

        Returns:
            Tuple of (df_settlements, df_details).
            df_settlements contains match_hash_base; CardRepository adds counter.
        """
        self.logger(f"Aggregating {len(df_vouchers)} vouchers", "INFO")

        # 1. Normalize brand
        df_vouchers = self._normalize_brand_for_header(df_vouchers, brand)

        # 2. Group settlements
        df_settlements = self._group_settlements(df_vouchers)

        # 3. Sort chronologically
        df_settlements = self._sort_settlements(df_settlements)

        # 4. Generate match_hash_base (no counter)
        df_settlements = self._generate_match_hash_base(df_settlements)

        # 5. Generate etl_hash
        df_settlements = self._generate_settlement_etl_hash(df_settlements)

        # 6. Add metadata
        df_settlements = self._add_settlement_metadata(df_settlements)

        # 7. Prepare details
        df_details = self._prepare_details(df_vouchers)

        self.logger(
            f"Aggregation complete: {len(df_settlements)} settlements, "
            f"{len(df_details)} details",
            "SUCCESS"
        )

        return df_settlements, df_details

    def _normalize_brand_for_header(
        self,
        df: pd.DataFrame,
        default_brand: Optional[str]
    ) -> pd.DataFrame:
        """
        Normalize brand codes to canonical settlement header values.

        Mapping:
            Contains VISA      -> VISA
            Contains DINERS/DC -> DINERS CLUB
            Contains AMEX      -> AMEX
            Contains PACIFICARD -> PACIFICARD
            Other              -> original value or 'OTROS'
        """
        df = df.copy()

        if 'brand' in df.columns:
            def normalize_header_brand(b):
                b_str = str(b).upper().strip()
                if 'VISA' in b_str:
                    return 'VISA'
                elif 'DINERS' in b_str or b_str == 'DC':
                    return 'DINERS CLUB'
                elif 'AMEX' in b_str:
                    return 'AMEX'
                elif 'PACIFICARD' in b_str:
                    return 'PACIFICARD'
                else:
                    return b_str if b_str else 'OTROS'

            df['brand_header'] = df['brand'].apply(normalize_header_brand)

        elif default_brand:
            df['brand_header'] = default_brand.upper().strip()

        else:
            df['brand_header'] = 'OTROS'

        return df

    def _group_settlements(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Group vouchers by settlement and sum amount columns.

        Group keys: settlement_id, brand_header, establishment_name, fecha_pago.
        Aggregations: sum of all amount columns; count of voucher_hash_key records.
        """
        df_grouped = df.groupby([
            'settlement_id',
            'brand_header',
            'establishment_name',
            'fecha_pago'
        ]).agg({
            'amount_gross': 'sum',
            'amount_net': 'sum',
            'amount_commission': 'sum',
            'amount_tax_iva': 'sum',
            'amount_tax_irf': 'sum',
            'voucher_hash_key': 'count',
            'source_file': 'first',
            'lote': 'first' if 'lote' in df.columns else lambda x: None
        }).reset_index()

        df_grouped = df_grouped.rename(columns={
            'voucher_hash_key': 'count_voucher',
            'brand_header': 'brand',
            'fecha_pago': 'settlement_date',
            'lote': 'batch_number'
        })

        self.logger(f"Grouped into {len(df_grouped)} settlements", "INFO")

        return df_grouped

    def _sort_settlements(self, df: pd.DataFrame) -> pd.DataFrame:
        """Sort settlements by settlement_date then settlement_id for deterministic ordering."""
        return df.sort_values(
            by=['settlement_date', 'settlement_id']
        ).reset_index(drop=True)

    def _generate_match_hash_base(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate match_hash_base without the trailing counter suffix.

        Formats:
            PACIFICARD:  BRAND_BATCH_NET  (batch zero-padded to 6 digits)
                Example: PACIFICARD_001447_178.80
            All others:  BRAND_NET
                Example: DINERS CLUB_141.96

        The counter is appended by CardRepository after consulting
        card_hash_counters, ensuring globally unique match_hash_key values.
        """
        df['brand'] = df['brand'].astype(str).str.strip().str.upper()
        amount_net_str = DataCleaner.format_decimal_strict(df['amount_net'])

        mask_pacificard = df['brand'].str.contains('PACIFICARD', case=False, na=False)

        if mask_pacificard.any():
            df['batch_clean'] = (
                df['batch_number']
                .fillna('0')
                .astype(str)
                .str.replace(r'\.0$', '', regex=True)
                .str.zfill(6)
            )

            hash_base_pcf = (
                df['brand'] + "_" +
                df['batch_clean'] + "_" +
                amount_net_str
            )

            self.logger("Generating hash_base for PACIFICARD (format: BRAND_BATCH_NET)", "INFO")
        else:
            hash_base_pcf = None

        hash_base_std = df['brand'] + "_" + amount_net_str

        if mask_pacificard.any():
            df['match_hash_base'] = np.where(mask_pacificard, hash_base_pcf, hash_base_std)
        else:
            df['match_hash_base'] = hash_base_std

        df = df.drop(columns=['batch_clean'], errors='ignore')

        self.logger("Hash bases generated (no counter; Repository will append counters)", "SUCCESS")

        return df

    def _generate_settlement_etl_hash(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generate MD5 etl_hash from settlement_id + date + brand + establishment."""
        raw_str = (
            df['settlement_id'].astype(str) +
            df['settlement_date'].astype(str) +
            df['brand'].astype(str) +
            df['establishment_name'].astype(str)
        )

        df['etl_hash'] = raw_str.apply(lambda x: hashlib.md5(x.encode()).hexdigest())

        return df

    def _add_settlement_metadata(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add etl_batch_id and reconcile_status metadata columns."""
        df['etl_batch_id'] = f"ETL_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}"
        df['reconcile_status'] = 'PENDING'

        if 'batch_number' not in df.columns:
            df['batch_number'] = None

        return df

    def _prepare_details(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Rename voucher columns to staging schema names for stg_card_details.

        Mapping:
            settlement_id       -> settlement_id
            fecha_venta         -> voucher_date
            tarjeta_enmascarada -> card_number
            autorizacion        -> auth_code
            referencia          -> voucher_ref
            lote                -> batch_number
            amount_*            -> amount_*  (unchanged)
            brand               -> brand
            establishment_code  -> establishment_code
            establishment_name  -> establishment_name
            voucher_hash_key    -> voucher_hash_key
            etl_hash            -> etl_hash
            reconcile_status    -> reconcile_status
        """
        final_cols_map = {
            'settlement_id': 'settlement_id',
            'fecha_venta': 'voucher_date',
            'tarjeta_enmascarada': 'card_number',
            'autorizacion': 'auth_code',
            'referencia': 'voucher_ref',
            'lote': 'batch_number',
            'amount_gross': 'amount_gross',
            'amount_net': 'amount_net',
            'amount_commission': 'amount_commission',
            'amount_tax_iva': 'amount_tax_iva',
            'amount_tax_irf': 'amount_tax_irf',
            'brand': 'brand',
            'establishment_code': 'establishment_code',
            'establishment_name': 'establishment_name',
            'voucher_hash_key': 'voucher_hash_key',
            'etl_hash': 'etl_hash',
            'reconcile_status': 'reconcile_status'
        }

        df_details = df.rename(columns=final_cols_map)

        available_cols = [c for c in final_cols_map.values() if c in df_details.columns]

        return df_details[available_cols].copy()
